import pygame

character_sprites = pygame.sprite.Group()
location_sprites = pygame.sprite.Group()
ui_sprites = pygame.sprite.Group()
enemy_sprites = pygame.sprite.Group()
all_sprites = pygame.sprite.Group()
weapons_sprites = pygame.sprite.Group()
bullet_sprites = pygame.sprite.Group()
choosing_character_sprites = pygame.sprite.Group()
frames = pygame.sprite.Group()
walls = pygame.sprite.Group()
tiles = pygame.sprite.Group()
seller = pygame.sprite.Group()
camera_entities = pygame.sprite.Group()
seller_sprites = pygame.sprite.Group()
game_over_sprites = pygame.sprite.Group()
game_win_sprites = pygame.sprite.Group()